env:
  es2021: true
  node: true
  jest: true
extends:
  - airbnb-base
parserOptions:
  ecmaVersion: 12
  sourceType: module
rules:
  no-console: off
  import/extensions: off
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }]
